apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infoscale-dr-meta-bkp-pvc
  namespace: infoscale-vtas
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: infoscale-rootdisk-sc
