apiVersion: infoscale.veritas.com/v1
kind: DataReplication
metadata:
  name: openmrs-datarep
  namespace: infoscale-vtas
spec:
  lbEnabled: false
  remoteClusterDetails:
    - remoteLbEnabled: false
      remoteCloudVendor: Local
      clusterName: cluster-dr
      latencyProtection: disable
      logProtection: autodcm
      networkTransportProtocol: TCP
      remoteHostAddress: 10.10.20.11
      remoteNIC: br-ex
      remoteNetMask: 255.255.0.0
      replicationState: start
      replicationType: async
  cloudVendor: Local
  selector:
    namespace: openmrs
  currentPrimary: cluster-prod
  force: false
  localHostAddress: 10.10.10.11
  localNIC: br-ex
  localNetMask: 255.255.0.0
